version: '3.8'

services:
    backend: 
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: backend-taxi-api
      environment:
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - DB_HOST=${DB_HOST:-db}
        - DB_PORT=${DB_PORT:-3306}
        - DB_USERNAME=${DB_USERNAME:-root}
        - DB_PASSWORD=${DB_PASSWORD:-password}
        - DB_NAME=${DB_NAME:-taxi_app}
        - PORT=${PORT:-8080} 
      ports:
        - "8080:8080"
      volumes:
        - ./backend:/usr/src/app
      depends_on:
        - db
      networks:
        - taxi-network

    db:
      image: mysql:8.0
      container_name: taxi-db
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: taxi_app
      ports:
        - "3306:3306"
      volumes:
        - db-data:/var/lib/mysql
      networks:
        - taxi-network

    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: frontend-taxi-app
      ports:
        - "80:80"
      environment:
        - NEXT_PUBLIC_API_URL=http://backend:8080
        - NEXT_PUBLIC_GOOGLE_API_KEY=${GOOGLE_API_KEY}
      networks:
        - taxi-network
      depends_on:
        - backend

networks:
  taxi-network:
    driver: bridge

volumes: 
  db-data:
