export const TYPES = {
  RideService: Symbol.for('RideService'),
  RideController: Symbol.for('RideController'),
  RideRoutes: Symbol.for('RideRoutes'),
  RideRepository: Symbol.for('RideRepository'),
  CustomerRepository: Symbol.for('CustomerRepository'),
  DriverRepository: Symbol.for('DriverRepository'),
  GoogleMapsDataSource: Symbol.for('GoogleMapsDataSource'),
  EstimateRideUseCase: Symbol.for('EstimateRideUseCase'),
  GetRideHistoryUseCase: Symbol.for('GetRideHistoryUseCase'),
  ConfirmRideUseCase: Symbol.for('ConfirmRideUseCase'),
  DataSource: Symbol('DataSource'),
  DriverSeedService: Symbol.for('DriverSeedService'),
  CustomerSeedService: Symbol.for('CustomerSeedService'),
  RideSeedService: Symbol.for('RideSeedService'),
};
